project:
  type: website
  output-dir: ..

website:
  title: "Nic Steyn"
  search: false
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: papers.qmd
        text: Research outputs

format:
  html:
    theme: simplex
    css: styles.css
    toc: false



